### ISSUE TITLE
Unable to install plugin on Vagrant 2.2.5

### ISSUE THREAD

**Issue by kalpik** [cassianoleal/vagrant-butcher#63]
Hello,

I get the following error on vagrant 2.2.5.

```
> vagrant plugin install vagrant-butcher
Installing the 'vagrant-butcher' plugin. This can take a few minutes...
Building native extensions.  This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: C:/Users/knigam/.vagrant.d/gems/2.4.6/gems/nio4r-2.3.1/ext/nio4r
C:/HashiCorp/Vagrant/embedded/mingw64/bin/ruby.exe -r ./siteconf20190701-27496-lua0c.rb extconf.rb

current directory: C:/Users/knigam/.vagrant.d/gems/2.4.6/gems/nio4r-2.3.1/ext/nio4r
make "DESTDIR=" clean

current directory: C:/Users/knigam/.vagrant.d/gems/2.4.6/gems/nio4r-2.3.1/ext/nio4r
make "DESTDIR="

make failed, uncaught signal 11

Gem files will remain installed in C:/Users/knigam/.vagrant.d/gems/2.4.6/gems/nio4r-2.3.1 for inspection.
Results logged to C:/Users/knigam/.vagrant.d/gems/2.4.6/extensions/x64-mingw32/2.4.0/nio4r-2.3.1/gem_make.out
```

**Comment by cassianoleal** [comment]
Hi @kalpik 

Unfortunately I don't have access to a Windows machine to test a setup similar to yours. It does work on both my computers (running on macOS and Linux) but of course knowing that won't help you.

I have published a tentative version of the plugin with updated dependencies. Given that the problem you're having is while trying to build the C extensions of a dependency it might help. Please try to install it by running:

```
vagrant plugin install vagrant-butcher --plugin-version 2.3.2.pre
```

If you confirm that it works I'll publish a non-pre version with the updated dependencies.

Thanks!

**Comment by kalpik** [comment]
Hello @cassianoleal 

Thanks for the quick response. But the problem remains :(

`vagrant plugin install vagrant-butcher --plugin-version 2.3.2.pre
Installing the 'vagrant-butcher --version '2.3.2.pre'' plugin. This can take a few minutes...
Building native extensions.  This could take a while...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

ERROR: Failed to build gem native extension.

    current directory: C:/Users/knigam/.vagrant.d/gems/2.4.6/gems/nio4r-2.3.1/ext/nio4r
C:/HashiCorp/Vagrant/embedded/mingw64/bin/ruby.exe -r ./siteconf20190703-9476-1c0wkxt.rb extconf.rb

current directory: C:/Users/knigam/.vagrant.d/gems/2.4.6/gems/nio4r-2.3.1/ext/nio4r
make "DESTDIR=" clean

current directory: C:/Users/knigam/.vagrant.d/gems/2.4.6/gems/nio4r-2.3.1/ext/nio4r
make "DESTDIR="

make failed, uncaught signal 11

Gem files will remain installed in C:/Users/knigam/.vagrant.d/gems/2.4.6/gems/nio4r-2.3.1 for inspection.
Results logged to C:/Users/knigam/.vagrant.d/gems/2.4.6/extensions/x64-mingw32/2.4.0/nio4r-2.3.1/gem_make.out`

**Comment by kalpik** [comment]
Okay, I just did a fresh re-install of vagrant, removing the install and .vagrant.d folder, and now the plugin installs fine! So I guess it was an issue with the upgrade from 2.2.4. Sorry to have wasted your time :(
